# Generated by Django 3.1.4 on 2021-01-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceInfo', '0002_auto_20210103_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givento',
            name='date',
            field=models.DateTimeField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='takenfrom',
            name='date',
            field=models.DateTimeField(default='', max_length=255),
        ),
    ]
