# Generated by Django 3.1.4 on 2021-01-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceInfo', '0003_auto_20210103_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givento',
            name='barcode',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='takenfrom',
            name='barcode',
            field=models.IntegerField(default=''),
        ),
    ]
